ENCHANTMENTS := [
    "Strength",
    "Agility",
    "Dexterity",
    "Will",
    "Knowledge",
    "Vigor",
    "Resourcefulness",
    "Armor Penetration",
    "Additional Physical Damage",
    "True Physical Damage",
    "Physical Damage Bonus",
    "Physical Weapon Damage",
    "Physical Power",
    "Magic Penetration",
    "Additional Magical Damage",
    "True Magical Damage",
    "Magical Damage Bonus",
    "Magical Power",
    "Armor Rating",
    "Magic Resistance",
    "Physical Damage Reduction",
    "Magical Damage Reduction",
    "Projectile Damage Reduction",
    "Action Speed",
    "Move Speed",
    "Move Speed Bonus",
    "Regular Interaction Speed",
    "Magical Interaction Speed",
    "Spell Casting Speed",
    "Max Health",
    "Max Health Bonus",
    "Physical Healing",
    "Magical Healing",
    "Buff Duration Bonus",
    "Debuff Duration Bonus",
    "Memory Capacity",
    "Memory Capacity Bonus",
    "Luck",
    "Additional Weapon Damage"
]

ITEMS := [
    "Arming Sword",
    "Crystal Sword",
    "Falchion",
    "Longsword",
    "Rapier",
    "Short Sword",
    "Viking Sword",
    "Blade of Righteousness",
    "Demon's Glee",
    "Divine Blade",
    "Divine Short Sword",
    "Falchion of Honor",
    "Golden Viking Sword",
    "Short Sword of Righteousness",
    "Sterling Blade",
    "Boneshaper",
    "Divine Rod",
    "Divine Staff",
    "Light Bringer",
    "Rod of Righteousness",
    "Staff of Righteousness",
    "Sterling Rod",
    "Sterling Staff",
    "Castillon Dagger",
    "Kris Dagger",
    "Rondel Dagger",
    "Stiletto Dagger",
    "Dagger of Righteousness",
    "Divine Dagger",
    "Sterling Dagger",
    "Throwing Knife",
    "Bardiche",
    "Halberd",
    "Spear",
    "Spear of Rot",
    "Battle Axe",
    "Double Axe",
    "Felling Axe",
    "Hatchet",
    "Horseman's Axe",
    "Axe of Righteousness",
    "Divine Axe",
    "Francisca Axe",
    "Golden Felling Axe",
    "Sterling Axe",
    "Longbow",
    "Recurve Bow",
    "Survival Bow",
    "Crossbow",
    "Hand Crossbow",
    "Windlas Crossbow",
    "Ceremonial Staff",
    "Crystal Ball",
    "Magic Staff",
    "Spellbook",
    "Buckler",
    "Heater Shield",
    "Pavise",
    "Round Shield",
    "Armet",
    "Barbuta Helm",
    "Chapel De Fer",
    "Chaperon",
    "Cobalt Chapel De Fer",
    "Cobalt Hat",
    "Cobalt Hood",
    "Cobalt Viking Helm",
    "Copperlight Kettle Hat",
    "Copperlight Shadow Hood",
    "Copperlight Straw Hat",
    "Cowl of Darkness",
    "Crusader Helm",
    "Darkgrove Hood",
    "Dread Hood",
    "Elkwood Crown",
    "Feathered Hat",
    "Forest Hood",
    "Gjermundbu",
    "Golden Armet",
    "Golden Gjermundbu",
    "Golden Hounskull",
    "Golden Leaf Hood",
    "Golden Scarf",
    "Great Helm",
    "Hounskull",
    "Kettle Hat",
    "Leather Bonnet",
    "Leather Cap",
    "Norman Nasal Helm",
    "Occultist Hood",
    "Open Sallet",
    "Ranger Hood",
    "Rogue Cowl",
    "Rubysilver Barbuta Helm",
    "Rubysilver Cap",
    "Rubysilver Hood",
    "Sallet",
    "Shadow Hood",
    "Shadow Mask",
    "Spangenhelm",
    "Straw Hat",
    "Topfhelm",
    "Viking Helm",
    "Visored Barbuta Helm",
    "Visored Sallet",
    "Wizard Hat",
    "Adventurer Tunic",
    "Champion Armor",
    "Cobalt Frock",
    "Cobalt Regal Gambeson",
    "Cobalt Templar Armor",
    "Copperlight Attire",
    "Copperlight Outfit",
    "Copperlight Sanctum Plate Armor",
    "Copperlight Tunic",
    "Crusader Armor",
    "Dark Cuirass",
    "Dark Plate Armor",
    "Darkgrove Robe",
    "Doublet",
    "Fine Cuirass",
    "Frock",
    "Golden Padded Tunic",
    "Golden Plate",
    "Golden Robe",
    "Grand Brigandine",
    "Heavy Gambeson",
    "Light Aketon",
    "Marauder Outfit",
    "Mystic Vestments",
    "Northern Full Tunic",
    "Occultist Robe",
    "Occultist Tunic",
    "Oracle Robe",
    "Ornate Jazerant",
    "Padded Tunic",
    "Pourpoint",
    "Regal Gambeson",
    "Ritual Robe",
    "Robe of Darkness",
    "Rubysilver Cuirass",
    "Rubysilver Doublet",
    "Rubysilver Vestments",
    "Studded Leather",
    "Templar Armor",
    "Tri-Pelt Doublet",
    "Tri-Pelt Northern Full Tunic",
    "Troubadour Outfit",
    "Wanderer Attire",
    "Warden Outfit",
    "Bardic Pants",
    "Brave Hunter's Pants",
    "Cloth Pants",
    "Cobalt Plate Pants",
    "Cobalt Trousers",
    "Copperlight Leggings",
    "Copperlight Pants",
    "Copperlight Plate Pants",
    "Dark Leather Leggings",
    "Demonclad Leggings",
    "Golden Chausses",
    "Golden Leggings",
    "Heavy Leather Leggings",
    "Leather Chausses",
    "Leather Leggings",
    "Loose Trousers",
    "Occultist Pants",
    "Padded Leggings",
    "Plate Pants",
    "Rubysilver Leggings",
    "Rubysilver Plate Pants",
    "Wolf Hunter Leggings",
    "Cobalt Heavy Gauntlet",
    "Cobalt Leather Gloves",
    "Copperlight Gauntlets",
    "Copperlight Riveted Gloves",
    "Demon Grip Gloves",
    "Elkwood Gloves",
    "Gloves of Utility",
    "Golden Gauntlets",
    "Golden Gloves",
    "Gravewolf Gloves",
    "Heavy Gauntlets",
    "Leather Gloves",
    "Light Gauntlets",
    "Mystic Gloves",
    "Rawhide Gloves",
    "Reinforced Gloves",
    "Riveted Gloves",
    "Rubysilver Gauntlets",
    "Rubysilver Rawhide Gloves",
    "Runestone Gloves",
    "Adventurer Boots",
    "Buckled Boots",
    "Cobalt Lightfoot Boots",
    "Cobalt Plate Boots",
    "Copperlight Lightfoot Boots",
    "Copperlight Plate Boots",
    "Darkleaf Boots",
    "Dashing Boots",
    "Forest Boots",
    "Foul Boots",
    "Golden Boots",
    "Golden Plate Boots",
    "Heavy Boots",
    "Laced Turnshoe",
    "Lightfoot Boots",
    "Low Boots",
    "Occultist Boots",
    "Old Shoes",
    "Plate Boots",
    "Rubysilver Adventurer Boots",
    "Rubysilver Plate Boots",
    "Rugged Boots",
    "Shoes of Darkness",
    "Stitched Turnshoe",
    "Turnshoe",
    "Wizard Shoes",
    "Adventurer Cloak",
    "Cloak of Darkness",
    "Bandage",
    "Bat Claw",
    "Bear Pendant",
    "Beetle Wings",
    "Dlus Eunhalle",
    "Bug Shell",
    "Campfire Kit",
    "Candy Cane",
    "Captured Mana Flakes",
    "Centaur Hoof",
    "Centaur Horn",
    "Centaur Tail",
    "Centaur's Madness",
    "Ancient Scroll (Cracked)",
    "Arrow",
    "Blue Eyeballs",
    "Blue Sapphire (Cracked)",
    "Bolt",
    "Bone",
    "Bow of Righteousness",
    "Bowstring",
    "Broken Skull",
    "Cobalt Powder",
    "Cockatrice's Lucky Feather",
    "Copper Ingot",
    "Copper Ore",
    "Copper Powder",
    "Ceremonial Dagger (Cracked)",
    "Cursed Crown",
    "Cyclops Eye",
    "Cyclops Rags",
    "Cyclops Vision Crystal",
    "Cyclops's Club",
    "Dark Matter",
    "Demon Blood",
    "Demon Dog Thorn",
    "Diamond (Cracked)",
    "Divine Bow",
    "Dog Collar",
    "Dotted Gold Bangle (Cracked)",
    "Drum",
    "Emerald (Cracked)",
    "Enchanted Dark Fabric",
    "Explosive Bottle",
    "Extra Thick Pelts",
    "Fangs of Death Necklace",
    "Firefly's Abdomen",
    "Flanged Mace",
    "Flute",
    "Frost Amulet",
    "Frost Wyvern Egg",
    "Frost Wyvern's Claws",
    "Frostlight Abyss Plate Armor",
    "Frostlight Aketon",
    "Frostlight Cloak",
    "Frostlight Crusader Helm",
    "Frostlight Crystal Sword",
    "Frostlight Feathered Hat",
    "Frostlight Gauntlets",
    "Frostlight Hood",
    "Frostlight Lantern Shield",
    "Frostlight Leather Leggings",
    "Frostlight Mystic Gloves",
    "Frostlight Norman Nasal Helm",
    "Frostlight Oracle Robe",
    "Frostlight Plate Boots",
    "Frostlight Plate Pants",
    "Frostlight Riveted Gloves",
    "Frostlight Rugged Boots",
    "Frostlight Runestone Gloves",
    "Frostlight Spear",
    "Frostlight Trousers",
    "Frostlight Warden Outfit",
    "Frostlight Wizard Hat",
    "Froststone Ingot",
    "Froststone Ore",
    "Froststone Powder",
    "Frozen Heart",
    "Frozen Iron Key",
    "Gem Necklace (Cracked)",
    "Gem Ring (Cracked)",
    "Ghostly Essence",
    "Giant Toe",
    "Gingerbread Cookie",
    "Glimmer Bangle (Cracked)",
    "Glowing Blue Ice Eyes",
    "Goblet (Cracked)",
    "Goblin Ear",
    "Gold Band (Cracked)",
    "Gold Bowl (Cracked)",
    "Gold Candelabra (Cracked)",
    "Gold Candle Holder (Cracked)",
    "Gold Candle Platter (Cracked)",
    "Gold Chalice (Cracked)",
    "Gold Coin",
    "Gold Coin Bag",
    "Gold Coin Chest",
    "Gold Coin Purse",
    "Gold Crown (Cracked)",
    "Gold Goblet (Cracked)",
    "Gold Ingot",
    "Gold Ore",
    "Gold Powder",
    "Gold Waterpot (Cracked)",
    "Golden Key",
    "Golden Teeth",
    "Grave Essence",
    "Grimslayer",
    "Grimsmile Ring",
    "Heart Candy",
    "Heavy Roots",
    "Icefang",
    "Infected Flesh",
    "Intact Skull",
    "Iron Ingot",
    "Iron Ore",
    "Iron Powder",
    "Kobold's Ear",
    "Lantern",
    "Lantern Shield",
    "Leaf Gold Bangle (Cracked)",
    "Lifeleaf",
    "Lockpick",
    "Lute",
    "Lyre",
    "Maggots",
    "Magic Protection Potion",
    "Mana Sphere",
    "Mercurial Cloak",
    "Mimic Tongue",
    "Mimic Tooth",
    "Moldy Bread",
    "Monkey Pendant",
    "Morning Star",
    "Mystical Gem",
    "Necklace of Peace",
    "Old Cloth",
    "Old Rusty Key",
    "Patterned Gold Bangle (Cracked)",
    "Phantom Flower",
    "Phoenix Choker",
    "Pickaxe",
    "Dlate Denta",
    "Potion of Clarity",
    "Potion of Healing",
    "Potion of Invisibility",
    "Potion of Luck",
    "Potion of Protection",
    "Primitive Bracelet",
    "Quarterstaff",
    "Radiant Cloak",
    "Rat Pendant",
    "Ring of Courage",
    "Ring of Finesse",
    "Ring of Quickness",
    "Ring of Resolve",
    "Ring of Survival",
    "Ring of Vitality",
    "Ring of Wisdom",
    "Rotten Fluids",
    "Ruby (Cracked)",
    "Rubysilver Ingot",
    "Rubysilver Ore",
    "Rubysilver Powder",
    "Dubai Dauhida Claves",
    "Rusty Broken Sword",
    "Shine Bangle (Cracked)",
    "Silver Chalice (Cracked)",
    "Silver Coin",
    "Silver Ingot",
    "Silver Ore",
    "Silver Powder",
    "Simple Gold Bangle (Cracked)",
    "Skull Key",
    "Slim Bangle (Cracked)",
    "Sovereign's Ghostblade",
    "Spider Silk",
    "Splendid Cloak",
    "Sterling Bow",
    "Token of Honor",
    "Torch",
    "Torn Bat Wing",
    "Torq of Soul",
    "Trap Disarming Kit",
    "Triple Gem Bangle (Cracked)",
    "Troll Pelt",
    "Troll's Blood",
    "Troll's Club",
    "Troll's Bane",
    "Turquoise Gem Bangle (Cracked)",
    "Vigilant Cloak",
    "Void Blade",
    "Volcanic Ash",
    "Wardweed",
    "Warlord's Broken Sword Blade",
    "Watchman Cloak",
    "Wendigo's Hoof",
    "Wendigo's Sharp Claws",
    "Wind Locket",
    "Wolf Claw",
    "Wolf Fang",
    "Wolf Pelt",
    "Yeti's Teeth",
    "Zweihander"
]
