ENCHANTMENTS := [
    "Strength",
    "Agility",
    "Dexterity",
    "Will",
    "Knowledge",
    "Vigor",
    "Resourcefulness",
    "Armor Penetration",
    "Additional Physical Damage",
    "True Physical Damage",
    "Physical Damage Bonus",
    "Physical Weapon Damage",
    "Physical Power",
    "Magic Penetration",
    "Additional Magical Damage",
    "True Magical Damage",
    "Magical Damage Bonus",
    "Magical Power",
    "Armor Rating",
    "Magic Resistance",
    "Physical Damage Reduction",
    "Magical Damage Reduction",
    "Projectile Damage Reduction",
    "Action Speed",
    "Move Speed",
    "Move Speed Bonus",
    "Regular Interaction Speed",
    "Magical Interaction Speed",
    "Spell Casting Speed",
    "Max Health",
    "Max Health Bonus",
    "Physical Healing",
    "Magical Healing",
    "Buff Duration Bonus",
    "Debuff Duration Bonus",
    "Memory Capacity",
    "Memory Capacity Bonus",
    "Luck",
    "Additional Weapon Damage"
]

ITEMS := [
    "Arming Sword",
    "Crystal Sword",
    "Falchion",
    "Longsword",
    "Rapier",
    "Short Sword",
    "Viking Sword",
    
    "Blade of Righteousness",
    "Demon's Glee",
    "Divine Blade",
    "Divine Short Sword",
    "Falchion of Honor",
    "Golden Viking Sword",
    "Short Sword of Righteousness",
    "Sterling Blade",
    
    "Boneshaper",
    "Divine Rod",
    "Divine Staff",
    "Light Bringer",
    "Rod of Righteousness",
    "Staff of Righteousness",
    "Sterling Rod",
    "Sterling Staff",
    
    "Castillon Dagger",
    "Kris Dagger",
    "Rondel Dagger",
    "Stiletto Dagger",
    "Dagger of Righteousness",
    "Divine Dagger",
    "Sterling Dagger",
    "Throwing Knife",
    
    "Bardiche",
    "Halberd",
    "Spear",
    "Spear of Rot",
    
    "Battle Axe",
    "Double Axe",
    "Felling Axe",
    "Hatchet",
    "Horseman's Axe",
    "Axe of Righteousness",
    "Divine Axe",
    "Francisca Axe",
    "Golden Felling Axe",
    "Sterling Axe",
    
    "Longbow",
    "Recurve Bow",
    "Survival Bow",
    
    "Crossbow",
    "Hand Crossbow",
    "Windlas Crossbow",
    
    "Ceremonial Staff",
    "Crystal Ball",
    "Magic Staff",
    "Spellbook",
    
    "Buckler",
    "Heater Shield",
    "Pavise",
    "Round Shield",
    
    "Armet",
    "Barbuta Helm",
    "Chapel De Fer",
    "Chaperon",
    "Cobalt Chapel De Fer",
    "Cobalt Hat",
    "Cobalt Hood",
    "Cobalt Viking Helm",
    "Copperlight Kettle Hat",
    "Copperlight Shadow Hood",
    "Copperlight Straw Hat",
    "Cowl of Darkness",
    "Crusader Helm",
    "Darkgrove Hood",
    "Dread Hood",
    "Elkwood Crown",
    "Feathered Hat",
    "Forest Hood",
    "Gjermundbu",
    "Golden Armet",
    "Golden Gjermundbu",
    "Golden Hounskull",
    "Golden Leaf Hood",
    "Golden Scarf",
    "Great Helm",
    "Hounskull",
    "Kettle Hat",
    "Leather Bonnet",
    "Leather Cap",
    "Norman Nasal Helm",
    "Occultist Hood",
    "Open Sallet",
    "Ranger Hood",
    "Rogue Cowl",
    "Rubysilver Barbuta Helm",
    "Rubysilver Cap",
    "Rubysilver Hood",
    "Sallet",
    "Shadow Hood",
    "Shadow Mask",
    "Spangenhelm",
    "Straw Hat",
    "Topfhelm",
    "Viking Helm",
    "Visored Barbuta Helm",
    "Visored Sallet",
    "Wizard Hat",
    
    "Adventurer Tunic",
    "Champion Armor",
    "Cobalt Frock",
    "Cobalt Regal Gambeson",
    "Cobalt Templar Armor",
    "Copperlight Attire",
    "Copperlight Outfit",
    "Copperlight Sanctum Plate Armor",
    "Copperlight Tunic",
    "Crusader Armor",
    "Dark Cuirass",
    "Dark Plate Armor",
    "Darkgrove Robe",
    "Doublet",
    "Fine Cuirass",
    "Frock",
    "Golden Padded Tunic",
    "Golden Plate",
    "Golden Robe",
    "Grand Brigandine",
    "Heavy Gambeson",
    "Light Aketon",
    "Marauder Outfit",
    "Mystic Vestments",
    "Northern Full Tunic",
    "Occultist Robe",
    "Occultist Tunic",
    "Oracle Robe",
    "Ornate Jazerant",
    "Padded Tunic",
    "Pourpoint",
    "Regal Gambeson",
    "Ritual Robe",
    "Robe of Darkness",
    "Rubysilver Cuirass",
    "Rubysilver Doublet",
    "Rubysilver Vestments",
    "Studded Leather",
    "Templar Armor",
    "Tri-Pelt Doublet",
    "Tri-Pelt Northern Full Tunic",
    "Troubadour Outfit",
    "Wanderer Attire",
    "Warden Outfit",
    
    "Bardic Pants",
    "Brave Hunter's Pants",
    "Cloth Pants",
    "Cobalt Plate Pants",
    "Cobalt Trousers",
    "Copperlight Leggings",
    "Copperlight Pants",
    "Copperlight Plate Pants",
    "Dark Leather Leggings",
    "Demonclad Leggings",
    "Golden Chausses",
    "Golden Leggings",
    "Golden Plate Pants",
    "Heavy Leather Leggings",
    "Leather Chausses",
    "Leather Leggings",
    "Loose Trousers",
    "Occultist Pants",
    "Padded Leggings",
    "Plate Pants",
    "Rubysilver Leggings",
    "Rubysilver Plate Pants",
    "Wolf Hunter Leggings",
    
    "Cobalt Heavy Gauntlet",
    "Cobalt Leather Gloves",
    "Copperlight Gauntlets",
    "Copperlight Riveted Gloves",
    "Demon Grip Gloves",
    "Elkwood Gloves",
    "Gloves of Utility",
    "Golden Gauntlets",
    "Golden Gloves",
    "Gravewolf Gloves",
    "Heavy Gauntlets",
    "Leather Gloves",
    "Light Gauntlets",
    "Mystic Gloves",
    "Rawhide Gloves",
    "Reinforced Gloves",
    "Riveted Gloves",
    "Rubysilver Gauntlets",
    "Rubysilver Rawhide Gloves",
    "Runestone Gloves",
    
    "Adventurer Boots",
    "Buckled Boots",
    "Cobalt Lightfoot Boots",
    "Cobalt Plate Boots",
    "Copperlight Lightfoot Boots",
    "Copperlight Plate Boots",
    "Darkleaf Boots",
    "Dashing Boots",
    "Forest Boots",
    "Foul Boots",
    "Golden Boots",
    "Golden Plate Boots",
    "Heavy Boots",
    "Laced Turnshoe",
    "Lightfoot Boots",
    "Low Boots",
    "Occultist Boots",
    "Old Shoes",
    "Plate Boots",
    "Rubysilver Adventurer Boots",
    "Rubysilver Plate Boots",
    "Rugged Boots",
    "Shoes of Darkness",
    "Stitched Turnshoe",
    "Turnshoe",
    "Wizard Shoes",
    
    "Adventurer Cloak",
    "Cloak of Darkness",
    "Golden Cloak",
    "Mercurial Cloak",
    "Radiant Cloak",
    "Splendid Cloak",
    "Tattered Cloak",
    "Vigilant Cloak",
    "Watchman Cloak",
    
    "Badger Pendant",
    "Bear Pendant",
    "Fangs of Death Necklace",
    "Fox Pendant",
    "Frost Amulet",
    "Monkey Pendant",
    "Necklace of Peace",
    "Owl Pendant",
    "Ox Pendant",
    
    "Ring of Vitality",
    "Grimsmile Ring",
    "Ring of Courage",
    "Ring of Finesse",
    "Ring of Quickness",
    "Ring of Resolve",
    "Ring of Survival",
    "Ring of Wisdom",
    
    "Wolf Pelt",
    "Troll Pelt",
    "Iron Ore",
    "Cobalt Ore",
    "Copper Ore",
    "Explosive Bottle",
    "Oil Lantern",
    "Surgical Kit",
    "Centaur Hoof",
    "Wind Locket",
    "Phoenix Choker",
    
    "Flanged Mace",
    "Quarterstaff",
    "Zweihander",
    "War Hammer",
    "War Maul",
    
    "Bandage",
    "Bat Claw",
    "Beetle Wings",
    "Dlus Eunhalle",
    "Bug Shell",
    "Campfire Kit",
    "Candy Cane",
    "Captured Mana Flakes",
    "Arrow",
    "Badger Pendant",
    "Blue Eyeballs",
    "Blue Sapphire (Cracked)",
    "Bolt",
    "Bone",
    "Bow of Righteousness",
    "Bowstring",
    "Broken Skull",
    "Cobalt Powder",
    "Cobalt Viking Helm",
    "Cockatrice's Lucky Feather",
    "Copper Ingot",
    "Copper Powder",
    "Cobalt Frock",
    "Cobalt Hat",
    "Cobalt Heavy Gauntlet",
    "Cobalt Hood",
    "Cobalt Ingot",
    "Cobalt Leather Gloves",
    "Cobalt Lightfoot Boots",
    "Cobalt Plate Boots",
    "Cobalt Plate Pants",
    "Copperlight Attire",
    "Copperlight Gauntlets",
    "Copperlight Kettle Hat",
    "Copperlight Leggings",
    "Copperlight Lightfoot Boots",
    "Copperlight Outfit",
    "Copperlight Pants",
    "Copperlight Plate Boots.",
    "Copperlight Plate Pants",
    "Copperlight Riveted Gloves",
    "Copperlight Sanctum Plate Armor",
    "Copperlight Tunic",
    "Dark Cuirass",
    "Dark Plate Armor",
    "Darkgrove Hood",
    "Darkgrove Robe",
    "Dark Leather Leggings",
    "Demonclad Leggings",
    "Demon Grip Gloves",
    "Demon's Glee",
    "Fangs of Death Necklace",
    "Feathered Hat",
    "Frost Essence",
    "Frost Amulet",
    "Golden Boots",
    "Golden Chausses",
    "Golden Felling Axe",
    "Golden Gjermundbu",
    "Golden Golden Plate",
    "Golden Leaf Hood",
    "Golden Plate Boots",
    "Golden Plate Pants",
    "Golden Robe",
    "Golden Scarf",
    "Gravewolf Gloves",
    "Kris Dagger",
    "Mystic Vestments",
    "Occultist Pants",
    "Occultist Robe",
    "Padded Tunic",
    "Rubysilver Cuirass",
    "Rubysilver Doublet",
    "Rubysilver Gauntlets",
    "Rubysilver Hood",
    "Rubysilver Leggings",
    "Rubysilver Plate Boots",
    "Rubysilver Vestments",
    "Shadow Mask",
    "Silver Mace",
    "Spear of Rot",
    "Sterling Blade",
    "Sterling Dagger",
    "Sterling Rod",
    "Sterling Staff",
    "Tri-Pelt Doublet",
    "Tri-Pelt Northern Full Tunic",
    "Viking Helm",
    "War Maul",
    "Wolf Hunter Leggings"
]
